spring:
  profiles:
    active: local # ?? ??? ? ?? ????? local(? ??? ??) ???? ??

---
# ??? 1. ?? ?? ?? (??????? ?? Run ? ?) ???
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    # ???? ??? ?? localhost:5432 ? ?? ??
    url: jdbc:postgresql://localhost:5432/klljs_db
    username: leejunheon
    password: password123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---

# ??? 2. ??/?? ?? (Dockerfile ? Docker Compose ?? ???) ???
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    # docker-compose.yml?? ??? ????? ??, ??? ??(:) ?? ???? ?????.
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-db:5432/klljs_db}
    username: ${SPRING_DATASOURCE_USERNAME:leejunheon}
    password: ${SPRING_DATASOURCE_PASSWORD:password123!}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false # ?? ????? ?? ??? ?? SQL ??? ??? ?? ????.